import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {Miniflare,convertV4MiniflareOptions} from 'miniflare';
import {digest} from '../src/security';

test('D1 heartbeat, CSRF, approval and one-use viewer tickets',async()=>{
  const origin='https://farmservers.sargentweb.com';
  const mf=new Miniflare(convertV4MiniflareOptions({workers:[{name:'test',modules:true,scriptPath:'dist/index.js',compatibilityDate:'2026-09-09',compatibilityFlags:['nodejs_compat'],d1Databases:['DB'],outboundService: async request => { const u=new URL(request.url); assert.equal(u.hostname,'origin-node-1.sargentweb.com'); assert.equal(request.headers.get('X-Central-Token'),'d'.repeat(64)); assert.equal(request.headers.get('CF-Access-Client-Secret'),'db-secret'); if(u.searchParams.get('route')==='api_node_server_action'){assert.ok(['start','stop','restart'].includes((await request.json() as {action:string}).action));return Response.json({ok:true});} if(u.searchParams.get('route')==='api_node_apply_updates'){return Response.json({ok:true,results:[{ok:true,instance_id:'game-1'}]});} assert.equal(request.headers.get('X-Forwarded-Proto'),'https'); if(u.pathname.includes('/web/')){assert.equal(request.headers.get('X-Central-Public'),'web');assert.equal(request.headers.get('X-Central-User'),null);} assert.match(request.headers.get('X-Forwarded-Host') || '',/^(game|console)-/); return new Response('<a href="http://172.20.0.3:18000/feed/map.jpg?code=test&amp;size=512">http://172.20.0.3:18000/feed/map.jpg?code=test&amp;size=512</a>',{headers:{'Content-Type':'text/html','X-Farmservers-Upstream-Origin':'http://172.21.0.3:18000'}}); },bindings:{NODE_TOKEN_KEY:'c'.repeat(64),APP_ORIGIN:origin,BOOTSTRAP_ADMIN_ID:'513527870258151439',NODE_GATEWAYS:JSON.stringify({'node-1':{origin:'https://origin-node-1.sargentweb.com',token:'b'.repeat(64),accessClientId:'test-id',accessClientSecret:'test-secret'}})}}]}));
  try{
    const db=await mf.getD1Database('DB');
    await db.exec(await readFile('migrations/0001_control_plane.sql','utf8'));
    await db.exec(await readFile('migrations/0013_discord_avatar.sql','utf8'));
    await db.exec(await readFile('migrations/0007_blocked_users.sql','utf8'));
    await db.exec(await readFile('migrations/0004_node_tokens.sql','utf8'));
    for(const file of ['0002_node_updates.sql','0003_release_withdrawal.sql','0005_node_version.sql','0006_notification_reads.sql','0008_node_gateways.sql','0012_edit_presence.sql','0014_node_notes.sql','0015_game_sync.sql'])await db.exec(await readFile('migrations/'+file,'utf8'));
    const sid='a'.repeat(64),time=Math.floor(Date.now()/1000);
    await db.prepare('INSERT INTO users(id,name,role,created) VALUES(?,?,?,?)').bind('513527870258151439','Test owner','admin',time).run();
    await db.prepare('INSERT INTO sessions VALUES(?,?,?,?)').bind(await digest(sid),'513527870258151439','csrf-test',time+3600).run();
    const headers={Cookie:'__Host-farmservers='+sid,Origin:origin,'X-CSRF-Token':'csrf-test','Content-Type':'application/json'};
    assert.equal((await mf.dispatchFetch(origin+'/api/game-status',{method:'POST',headers:{Cookie:headers.Cookie,'Content-Type':'application/json'},body:JSON.stringify({action:'bootstrap',enabled:false})})).status,403);
    const live=(body:unknown,h=headers)=>mf.dispatchFetch(origin+'/api/live',{method:'POST',headers:h,body:JSON.stringify(body)});
    await db.prepare('INSERT INTO users(id,name,role,created) VALUES(?,?,?,?)').bind('999999999999999999','Second admin','admin',time).run();
    await db.prepare('INSERT INTO sessions VALUES(?,?,?,?)').bind(await digest('second-admin'),'999999999999999999','other-csrf',time+3600).run();
    const otherHeaders={...headers,Cookie:'__Host-farmservers=second-admin','X-CSRF-Token':'other-csrf'};
    assert.equal((await live({resource:'node:node-1',editing:true},otherHeaders)).status,200);
    const presence=await (await live({resource:'node:node-1',editing:false})).json() as {editors:{name:string}[]};
    assert.equal(presence.editors[0].name,'Second admin');
    assert.equal((await (await live({resource:'node:node-2',editing:false})).json() as {editors:unknown[]}).editors.length,0);
    await db.prepare('UPDATE edit_presence SET expires=0').run();
    assert.equal((await (await live({resource:'node:node-1',editing:false})).json() as {editors:unknown[]}).editors.length,0);
    assert.equal((await live({resource:'invalid',editing:true})).status,422);
    await db.prepare("DELETE FROM sessions WHERE user_id='999999999999999999'").run();
    await db.prepare("DELETE FROM users WHERE id='999999999999999999'").run();
    let r=await mf.dispatchFetch(origin+'/api/nodes',{method:'POST',headers:{Cookie:headers.Cookie},body:'{}'});assert.equal(r.status,403);
    r=await mf.dispatchFetch(origin+'/api/nodes',{method:'POST',headers,body:JSON.stringify({id:'node-1',name:'Test node'})});assert.equal(r.status,200);
    const enrolled=await r.json() as {token:string};assert.match(enrolled.token,/^[a-f0-9]{64}$/);
    const notes=(body:unknown,h=headers)=>mf.dispatchFetch(origin+'/api/nodes/notes',{method:'POST',headers:h,body:JSON.stringify(body)});
    assert.equal((await notes({id:'node-1',notes:'Rack 2 - maintenance Friday',version:0})).status,200);
    assert.equal((await notes({id:'node-1',notes:'stale overwrite',version:0})).status,409);
    assert.equal((await notes({id:'node-1',notes:'Updated note',version:1})).status,200);
    assert.equal((await notes({id:'node-1',notes:'stale overwrite',version:1})).status,409);
    assert.equal((await notes({id:'missing',notes:'test',version:0})).status,404);
    assert.equal((await notes({id:'node-1',notes:'x'.repeat(10001),version:2})).status,422);
    const savedNotes=await (await mf.dispatchFetch(origin+'/api/nodes/notes?id=node-1',{headers})).json() as {notes:string;version:number;updatedBy:string};
    assert.equal(savedNotes.notes,'Updated note');assert.equal(savedNotes.version,2);assert.equal(savedNotes.updatedBy,'Test owner');

    await db.prepare('INSERT INTO nodes(id,name,token_hash) VALUES(?,?,?)').bind('node-2','Second node','test-hash').run();
    const gatewaySettings=(body:unknown)=>mf.dispatchFetch(origin+'/api/nodes/gateway',{method:'POST',headers,body:JSON.stringify(body)});
    r=await mf.dispatchFetch(origin+'/api/nodes/gateway?id=node-1',{headers});assert.equal(r.status,200);assert.equal(r.headers.get('Cache-Control'),'no-store');
    const settings=await r.json() as {source:string;hasToken:boolean};assert.equal(settings.source,'legacy');assert.equal(settings.hasToken,true);assert.equal(JSON.stringify(settings).includes('test-secret'),false);
    const gatewayBody={id:'node-1',origin:'https://origin-node-1.sargentweb.com',accessClientId:'test-id',token:'d'.repeat(64),accessClientSecret:'db-secret'};
    assert.equal((await gatewaySettings({...gatewayBody,origin:'https://evil.example'})).status,422);
    assert.equal((await gatewaySettings(gatewayBody)).status,200);
    const encrypted=await db.prepare('SELECT gateway_encrypted FROM nodes WHERE id=?').bind('node-1').first<{gateway_encrypted:string}>();assert.ok(encrypted?.gateway_encrypted);assert.equal(encrypted.gateway_encrypted.includes('db-secret'),false);
    assert.equal((await gatewaySettings({...gatewayBody,token:'',accessClientSecret:''})).status,200);
    r=await mf.dispatchFetch(origin+'/api/nodes/gateway?id=node-1',{headers});assert.equal((await r.json() as {source:string}).source,'database');
    assert.equal((await gatewaySettings({...gatewayBody,id:'node-2',token:'',accessClientSecret:''})).status,422);
    assert.equal((await mf.dispatchFetch(origin+'/api/nodes/gateway',{method:'POST',headers:{Cookie:headers.Cookie},body:JSON.stringify(gatewayBody)})).status,403);
    await db.prepare('DELETE FROM nodes WHERE id=?').bind('node-2').run();
    r=await mf.dispatchFetch(origin+'/api/notifications',{headers});assert.equal(r.status,200);
    const notices=await r.json() as {id:string;read:boolean}[];assert.ok(notices.length);assert.equal(notices[0].read,false);
    assert.equal((await mf.dispatchFetch(origin+'/api/notifications/read',{method:'POST',headers,body:JSON.stringify({ids:[notices[0].id]})})).status,200);
    assert.equal(((await (await mf.dispatchFetch(origin+'/api/notifications',{headers})).json()) as {read:boolean}[])[0].read,true);
    r=await mf.dispatchFetch(origin+'/api/users/create',{method:'POST',headers,body:JSON.stringify({id:'123456789012345678',name:'Read only user',role:'viewer'})});assert.equal(r.status,200);
    await db.prepare('INSERT INTO sessions VALUES(?,?,?,?)').bind(await digest('viewer-session'),'123456789012345678','viewer-csrf',time+3600).run();
    const viewerHeaders={Cookie:'__Host-farmservers=viewer-session',Origin:origin,'X-CSRF-Token':'viewer-csrf','Content-Type':'application/json'};
    assert.equal((await mf.dispatchFetch(origin+'/api/nodes',{headers:viewerHeaders})).status,200);
    assert.equal((await mf.dispatchFetch(origin+'/api/users',{headers:viewerHeaders})).status,403);
    assert.equal((await mf.dispatchFetch(origin+'/api/nodes/notes?id=node-1',{headers:viewerHeaders})).status,403);
    assert.equal((await notes({id:'node-1',notes:'forbidden',version:2},viewerHeaders)).status,403);
    assert.equal((await mf.dispatchFetch(origin+'/api/action',{method:'POST',headers:viewerHeaders,body:JSON.stringify({node:'node-1',instance_id:'game-1',action:'start'})})).status,403);
    assert.equal(((await (await mf.dispatchFetch(origin+'/api/notifications',{headers:viewerHeaders})).json()) as {read:boolean}[])[0].read,false);
    assert.equal((await mf.dispatchFetch(origin+'/api/users',{method:'POST',headers,body:JSON.stringify({id:'123456789012345678',role:'pending'})})).status,200);
    assert.equal((await mf.dispatchFetch(origin+'/api/nodes',{headers:viewerHeaders})).status,403);
    assert.equal((await (await mf.dispatchFetch(origin+'/api/me',{headers:viewerHeaders})).json() as {role:string}).role,'pending');
    assert.equal((await mf.dispatchFetch(origin+'/api/users',{method:'POST',headers,body:JSON.stringify({id:'123456789012345678',role:'operator'})})).status,200);
    assert.equal((await (await mf.dispatchFetch(origin+'/api/me',{headers:viewerHeaders})).json() as {role:string}).role,'operator');
    assert.equal((await mf.dispatchFetch(origin+'/api/live',{method:'POST',headers:viewerHeaders,body:JSON.stringify({resource:'page:users',editing:true})})).status,403);

    const edit=(body:unknown)=>mf.dispatchFetch(origin+'/api/nodes/update',{method:'POST',headers,body:JSON.stringify(body)});
    assert.equal((await edit({id:'node-1',name:'Renamed node',enabled:false})).status,200);
    let edited=await db.prepare('SELECT name,enabled,token_hash FROM nodes WHERE id=?').bind('node-1').first<{name:string;enabled:number;token_hash:string}>();
    assert.equal(edited?.name,'Renamed node');assert.equal(edited.enabled,0);assert.equal(edited.token_hash,await digest(enrolled.token));
    assert.equal((await edit({id:'node-1',name:'   ',enabled:true})).status,422);
    assert.equal((await edit({id:'missing',name:'Missing',enabled:true})).status,404);
    assert.equal((await edit({id:'node-1',name:'Test node',enabled:true})).status,200);
    r=await mf.dispatchFetch(origin+'/api/nodes',{method:'POST',headers,body:JSON.stringify({id:'node-1',name:'Duplicate',createOnly:true})});assert.equal(r.status,409);
    assert.equal((await db.prepare('SELECT token_hash FROM nodes WHERE id=?').bind('node-1').first<{token_hash:string}>())?.token_hash,await digest(enrolled.token));
    const reveal=()=>mf.dispatchFetch(origin+'/api/nodes/token',{method:'POST',headers,body:JSON.stringify({id:'node-1'})});
    r=await reveal();assert.equal(r.status,200);assert.equal(r.headers.get('Cache-Control'),'no-store');assert.equal((await r.json() as {token:string}).token,enrolled.token);
    const stored=await db.prepare('SELECT token_encrypted FROM nodes WHERE id=?').bind('node-1').first<{token_encrypted:string}>();
    assert.ok(stored?.token_encrypted);assert.equal(stored.token_encrypted.includes(enrolled.token),false);
    assert.equal((await mf.dispatchFetch(origin+'/api/nodes/token',{method:'POST',headers:{Cookie:headers.Cookie},body:JSON.stringify({id:'node-1'})})).status,403);
    assert.equal((await mf.dispatchFetch(origin+'/api/nodes/token',{method:'POST',headers:{Origin:origin},body:JSON.stringify({id:'node-1'})})).status,401);
    await db.prepare("UPDATE users SET role='operator'").run();assert.equal((await reveal()).status,403);
    assert.equal((await mf.dispatchFetch(origin+'/api/nodes/gateway',{method:'POST',headers,body:'{}'})).status,403);
    for(const path of ['/api/users','/users','/api/nodes/software?node=node-1','/api/history?node=node-1','/api/manage?node=node-1&operation=inventory','/api/notifications','/api/cloudflare','/api/audit','/api/nodes/notes?id=node-1','/api/game-status','/game-status'])assert.equal((await mf.dispatchFetch(origin+path,{headers})).status,403,path);
    for(const kind of ['panel','web','vnc'])assert.equal((await mf.dispatchFetch(origin+'/api/launch?node=node-1&instance=game-1&kind='+kind,{method:'POST',headers,body:'{}'})).status,403);
    for(const action of ['logs','backend_reboot'])assert.equal((await mf.dispatchFetch(origin+'/api/action',{method:'POST',headers,body:JSON.stringify({node:'node-1',instance_id:'game-1',action})})).status,403);
    for(const action of ['start','stop','restart'])assert.equal((await mf.dispatchFetch(origin+'/api/action',{method:'POST',headers,body:JSON.stringify({node:'node-1',instance_id:'game-1',action})})).status,200);
    assert.equal((await mf.dispatchFetch(origin+'/api/nodes/apply-updates',{method:'POST',headers,body:JSON.stringify({node:'node-1'})})).status,403);
    await db.prepare('UPDATE nodes SET snapshot=? WHERE id=?').bind(JSON.stringify({samples:[{scope:'host',data:{cpu_percent:99}}],servers:[{instance_id:'game-1',server_name:'Test game',status:'running',secret:'private'}]}),'node-1').run();
    const staffData=await (await mf.dispatchFetch(origin+'/api/nodes',{headers})).json() as {nodes:{snapshot:unknown}[]};
    assert.deepEqual(staffData.nodes[0].snapshot,{servers:[{instance_id:'game-1',server_name:'Test game',status:'running'}]});
    assert.equal((await mf.dispatchFetch(origin+'/nodes/node-1',{headers,redirect:'manual'})).headers.get('Location'),origin+'/servers');
    assert.equal((await edit({id:'node-1',name:'Unauthorized',enabled:false})).status,403);
    await db.prepare("UPDATE users SET role='admin'").run();
    r=await mf.dispatchFetch(origin+'/api/nodes/apply-updates',{method:'POST',headers,body:JSON.stringify({node:'node-1'})});
    assert.equal(r.status,200);
    assert.deepEqual(await r.json(),{ok:true,results:[{ok:true,instance_id:'game-1'}]});
    await db.prepare('UPDATE nodes SET token_encrypted=NULL').run();assert.equal((await reveal()).status,409);
    const payload={version:1,servers:[{instance_id:'game-1',server_name:'Test game',password:'excluded'}],samples:[{scope:'host',timestamp:time,data:{cpu_percent:12,password:'excluded'}}]};
    const heartbeat={method:'POST',headers:{Authorization:'Bearer '+enrolled.token},body:JSON.stringify(payload)};
    assert.equal((await mf.dispatchFetch(origin+'/api/heartbeat/node-1',heartbeat)).status,200);
    assert.equal((await (await reveal()).json() as {token:string}).token,enrolled.token);
    assert.equal((await mf.dispatchFetch(origin+'/api/heartbeat/node-1',heartbeat)).status,200);
    assert.equal((await db.prepare('SELECT COUNT(*) AS n FROM samples').first<{n:number}>())?.n,1);
    r=await mf.dispatchFetch(origin+'/api/nodes',{headers});const result=await r.text();assert.equal(result.includes('excluded'),false);assert.equal(result.includes(enrolled.token),false);
    r=await mf.dispatchFetch(origin+'/api/launch?node=node-1&kind=panel',{method:'POST',headers,body:'{}'});assert.equal(r.status,200);const launch=await r.json() as {url:string};
    assert.equal(launch.url,origin+'/nodes/node-1?tab=settings');
    r=await mf.dispatchFetch(origin+'/api/launch?node=node-1&kind=panel&instance=game-1',{method:'POST',headers,body:'{}'});
    assert.equal(r.status,200);const editorLaunch=await r.json() as {url:string};
    assert.equal(editorLaunch.url,origin+'/servers/node-1/game-1?tab=settings');
    await db.exec(await readFile('migrations/0016_game_endpoints.sql','utf8'));
    await db.exec(await readFile('migrations/0017_game_slot_ids.sql','utf8'));
    await db.prepare('INSERT INTO game_slots(node_id,instance) VALUES(?,?)').bind('node-1','game-1').run();
    for(const [kind,prefix] of [['web','game'],['vnc','console']])await db.prepare('INSERT INTO game_endpoints VALUES(?,?,?,?,1)').bind(prefix+'-fs25-0001.sargentweb.com','node-1','game-1',kind).run();
    await db.prepare('INSERT INTO game_endpoints VALUES(?,?,?,?,1)').bind('game-stale-host.sargentweb.com','node-1','game-2','web').run();
    await db.prepare('INSERT INTO game_endpoints(host,node_id,instance,kind) VALUES(?,?,?,?) ON CONFLICT(node_id,instance,kind) DO UPDATE SET host=excluded.host,ready=CASE WHEN host=excluded.host THEN ready ELSE 0 END').bind('game-fresh-host.sargentweb.com','node-1','game-2','web').run();
    const migrated=await db.prepare('SELECT host,ready FROM game_endpoints WHERE node_id=? AND instance=? AND kind=?').bind('node-1','game-2','web').all<{host:string;ready:number}>();
    assert.equal(migrated.results.length,1);
    assert.equal(migrated.results[0].host,'game-fresh-host.sargentweb.com');
    assert.equal(migrated.results[0].ready,0);
    r=await mf.dispatchFetch(origin+'/api/launch?node=node-1&kind=web&instance=game-1',{method:'POST',headers,body:'{}'});
    assert.equal(r.status,200);
    const webLaunch=await r.json() as {url:string};
    const viewerOrigin=new URL(webLaunch.url).origin;
    r=await mf.dispatchFetch(viewerOrigin+'/');
    assert.equal(r.status,200);
    const html=await r.text();
    assert.equal(html.includes('172.20.'),false);
    assert.ok(html.includes(viewerOrigin+'/feed/map.jpg?code=test&amp;size=512'));
    assert.equal(html.includes('&amp;amp;'),false);
    assert.equal(r.headers.has('X-Farmservers-Upstream-Origin'),false);
    assert.equal((await mf.dispatchFetch(viewerOrigin+'/',{method:'POST',headers:{Origin:'https://evil.example'},body:'bad'})).status,403);
    assert.equal((await mf.dispatchFetch('https://game-unknown.sargentweb.com/')).status,404);
    const consoleLaunch=await (await mf.dispatchFetch(origin+'/api/launch?node=node-1&kind=vnc&instance=game-1',{method:'POST',headers,body:'{}'})).json() as {url:string};
    const consoleOrigin=new URL(consoleLaunch.url).origin;
    assert.equal((await mf.dispatchFetch(consoleOrigin+'/')).status,401);
    const connected=await mf.dispatchFetch(consoleLaunch.url,{redirect:'manual'});assert.equal(connected.status,302);
    assert.equal((await mf.dispatchFetch(consoleLaunch.url,{redirect:'manual'})).status,401);
    assert.equal((await mf.dispatchFetch(consoleOrigin+'/',{headers:{Cookie:connected.headers.get('Set-Cookie')!.split(';')[0]}})).status,200);
    r=await mf.dispatchFetch(origin+'/api/nodes',{method:'POST',headers,body:JSON.stringify({id:'node-1',name:'Test node'})});
    const rotated=await r.json() as {token:string};assert.notEqual(rotated.token,enrolled.token);
    assert.equal((await mf.dispatchFetch(origin+'/api/heartbeat/node-1',heartbeat)).status,401);
    assert.equal((await (await reveal()).json() as {token:string}).token,rotated.token);
    const audits=await db.prepare("SELECT target FROM audit WHERE action='node.token-view'").all();assert.ok(audits.results.length>0);
    await db.prepare("UPDATE users SET role='pending'").run();
    assert.equal((await mf.dispatchFetch(origin+'/api/nodes',{headers})).status,403);
  } finally { await mf.dispose(); }
});
