import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {generateKeyPairSync,sign,createHash} from 'node:crypto';
import {Miniflare,convertV4MiniflareOptions} from 'miniflare';
import {digest} from '../src/security';

test('signed release distribution, authorization, immutable versions and job lifecycle',async()=>{
  const origin='https://farmservers.sargentweb.com',time=Math.floor(Date.now()/1000);
  const {publicKey,privateKey}=generateKeyPairSync('ed25519');
  const mf=new Miniflare(convertV4MiniflareOptions({workers:[{name:'releases-test',modules:true,scriptPath:'dist/index.js',compatibilityDate:'2026-09-09',compatibilityFlags:['nodejs_compat'],d1Databases:['DB'],r2Buckets:['RELEASES'],bindings:{APP_ORIGIN:origin,RELEASE_PUBLIC_KEY:publicKey.export({type:'spki',format:'der'}).toString('base64')}}]}));
  try {
    const db=await mf.getD1Database('DB');
    for(const file of ['0001_control_plane.sql','0002_node_updates.sql'])await db.exec(await readFile('migrations/'+file,'utf8'));
    await db.prepare('INSERT INTO users VALUES(?,?,?,?)').bind('owner','Owner','admin',time).run();
    await db.prepare('INSERT INTO sessions VALUES(?,?,?,?)').bind(await digest('session'),'owner','csrf',time+3600).run();
    await db.prepare('INSERT INTO nodes(id,name,token_hash) VALUES(?,?,?)').bind('node-1','Pilot',await digest('b'.repeat(64))).run();
    const admin={Cookie:'__Host-farmservers=session',Origin:origin,'X-CSRF-Token':'csrf','Content-Type':'application/json'};
    const node={Authorization:'Bearer '+'b'.repeat(64),'X-Node-ID':'node-1'};
    const req=(path:string,headers:Record<string,string>,body?:unknown)=>mf.dispatchFetch(origin+'/api/distribution/'+path,{headers,method:body===undefined?'GET':'POST',body:body===undefined?undefined:JSON.stringify(body)});
    const archive=Buffer.from('test archive bytes');
    const manifest=JSON.stringify({version:'v1.0.0',size:archive.length,sha256:createHash('sha256').update(archive).digest('hex')});
    const pkg={manifest,signature:sign(null,Buffer.from(manifest),privateKey).toString('base64'),archive:archive.toString('base64')};
    assert.equal((await req('releases',{},pkg)).status,401);
    assert.equal((await req('releases',{Cookie:admin.Cookie},pkg)).status,403);
    assert.equal((await req('releases',node,pkg)).status,404);
    assert.equal((await req('releases',admin,{...pkg,manifest:manifest.replace('v1.0.0','v1.0.1')})).status,422);
    assert.equal((await req('releases',admin,{...pkg,archive:Buffer.from('wrong').toString('base64')})).status,422);
    assert.equal((await req('releases',admin,pkg)).status,200);
    assert.equal((await req('releases',admin,pkg)).status,409);
    assert.equal((await req('releases/v1.0.0/archive',{})).status,401);
    assert.equal(await (await req('releases/v1.0.0/archive',node)).text(),archive.toString());
    assert.equal((await req('updates',node,{node:'node-1',version:'v1.0.0'})).status,404);
    await db.prepare("UPDATE users SET role='operator'").run();
    assert.equal((await req('updates',admin,{node:'node-1',version:'v1.0.0'})).status,403);
    await db.prepare("UPDATE users SET role='admin'").run();
    assert.equal((await req('updates',admin,{node:'node-1',version:'v1.0.0'})).status,200);
    assert.equal((await req('updates',admin,{node:'node-1',version:'v1.0.0'})).status,409);
    const claimed=await (await req('poll',node,{})).json() as {job:{id:string;version:string}};
    assert.equal(claimed.job.version,'v1.0.0');
    assert.deepEqual(await (await req('poll',node,{})).json(),claimed);
    assert.equal((await req('result',{...node,'X-Node-ID':'node-2'},{id:claimed.job.id,status:'succeeded'})).status,401);
    assert.deepEqual(await (await req('cancel',admin,{id:claimed.job.id})).json(),{ok:false});
    assert.equal((await req('result',node,{id:claimed.job.id,status:'succeeded'})).status,200);
    assert.deepEqual(await (await req('poll',node,{})).json(),{job:null});
    assert.equal((await db.prepare('SELECT status FROM node_updates').first<{status:string}>())?.status,'succeeded');
    await db.prepare('UPDATE nodes SET enabled=0').run();
    assert.equal((await req('releases/v1.0.0/archive',node)).status,401);
    assert.equal((await req('poll',node,{})).status,401);
    assert.equal((await req('updates',admin,{node:'node-1',version:'v1.0.0'})).status,409);
  } finally {await mf.dispose();}
});
