<?php
declare(strict_types=1);
require __DIR__ . '/../app/web/src/bootstrap.php';
function check(bool $condition): void { if (!$condition) { throw new RuntimeException('Gateway authorization regression'); } }
putenv('CENTRAL_GATEWAY_TOKEN=');
check(central_gateway_user() === null);
putenv('CENTRAL_GATEWAY_TOKEN=' . str_repeat('a', 64));
$_SERVER['HTTP_X_CENTRAL_USER'] = '513527870258151439';
$_SERVER['HTTP_X_CENTRAL_ROLE'] = 'admin';
$_SERVER['HTTP_X_CENTRAL_TOKEN'] = str_repeat('b', 64);
check(central_gateway_user() === null);
$_SERVER['HTTP_X_CENTRAL_TOKEN'] = str_repeat('a', 64);
check(central_gateway_user()['discord_id'] === '513527870258151439');
check(!isset($_SESSION['user']));
$_SERVER['HTTP_X_CENTRAL_ROLE'] = 'viewer';
check(central_gateway_user() === null);
$_SERVER['HTTP_X_CENTRAL_ROLE'] = 'operator';
$_SERVER['HTTP_X_CENTRAL_USER'] = "513527870258151439\n";
check(central_gateway_user() === null);
putenv('CENTRAL_GATEWAY_TOKEN=' . str_repeat('a', 64));
$expires = time() + 60;
$nonce = str_repeat('c', 32);
$mac = hash_hmac('sha256', 'console|fs25-001|' . $expires . '|' . $nonce, str_repeat('a', 64));
$uri = '/central/view/fs25-001/vnc/websockify/' . $expires . '.' . $nonce . '.' . $mac;
$origin = 'https://console-fs25-0001.sargentweb.com';
check(central_console_ticket_valid('fs25-001', $uri, $origin));
check(central_console_ticket_valid('fs25-001', $uri . '?x=1', $origin));
check(!central_console_ticket_valid('fs25-002', $uri, $origin));
check(!central_console_ticket_valid('fs25-001', $uri, null));
check(!central_console_ticket_valid('fs25-001', $uri, 'https://evil.example'));
check(!central_console_ticket_valid('fs25-001', $uri, 'http://console-fs25-0001.sargentweb.com'));
check(!central_console_ticket_valid('fs25-001', substr($uri, 0, -1) . ($mac[63] === '0' ? '1' : '0'), $origin));
check(!central_console_ticket_valid('fs25-001', '/central/view/fs25-001/vnc/websockify', $origin));
$stale = time() - 1;
check(!central_console_ticket_valid('fs25-001', '/central/view/fs25-001/vnc/websockify/' . $stale . '.' . $nonce . '.' . hash_hmac('sha256', 'console|fs25-001|' . $stale . '|' . $nonce, str_repeat('a', 64)), $origin));
putenv('CENTRAL_GATEWAY_TOKEN=' . str_repeat('b', 64));
check(!central_console_ticket_valid('fs25-001', $uri, $origin));
putenv('CENTRAL_GATEWAY_TOKEN=');
check(!central_console_ticket_valid('fs25-001', $uri, $origin));
echo "Gateway authorization and console ticket checks passed\n";
